// Generated by Supabase MCP — do not hand-edit.
// Regenerate: npx supabase gen types typescript --project-id fznliobjdeeyhictbepl > src/types/database.ts
// AX-102 complete: replaces the hand-written stopgap now that the project is provisioned.
//
// MANUAL ADDITION (pending regen): the `blocks` table + BlockRow alias were
// hand-added alongside migration 0001/0002 (RLS block support). Re-running the
// generator after the migration is applied will reproduce them; drop this note
// once it does.
//
// MANUAL ADDITION (pending regen): `profiles.bio` was hand-added alongside
// migration 0003 (AX-301 onboarding). Drop this note once regenerated.
//
// MANUAL ADDITION (pending regen): the `increment_listing_views` function was
// hand-added alongside migration 0006 (AX-111 view counter RPC). Drop this
// note once regenerated.
//
// Boundary rule: only src/repositories/ imports these types.
// Screens and hooks speak domain types from src/types/index.ts, never row types.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      blocks: {
        Row: {
          blocked_id: string
          blocker_id: string
          created_at: string
        }
        Insert: {
          blocked_id: string
          blocker_id: string
          created_at?: string
        }
        Update: {
          blocked_id?: string
          blocker_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "blocks_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "blocks_blocked_id_fkey"
            columns: ["blocked_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      listings: {
        Row: {
          category: string | null
          condition: string | null
          created_at: string
          description: string | null
          id: string
          image_urls: string[]
          is_free: boolean
          is_trade: boolean
          pickup: string | null
          price: number
          seller_id: string
          status: string
          title: string
          views: number
        }
        Insert: {
          category?: string | null
          condition?: string | null
          created_at?: string
          description?: string | null
          id?: string
          image_urls?: string[]
          is_free?: boolean
          is_trade?: boolean
          pickup?: string | null
          price?: number
          seller_id: string
          status?: string
          title: string
          views?: number
        }
        Update: {
          category?: string | null
          condition?: string | null
          created_at?: string
          description?: string | null
          id?: string
          image_urls?: string[]
          is_free?: boolean
          is_trade?: boolean
          pickup?: string | null
          price?: number
          seller_id?: string
          status?: string
          title?: string
          views?: number
        }
        Relationships: [
          {
            foreignKeyName: "listings_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          body: string
          created_at: string
          id: string
          listing_id: string | null
          receiver_id: string
          sender_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          listing_id?: string | null
          receiver_id: string
          sender_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          listing_id?: string | null
          receiver_id?: string
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_receiver_id_fkey"
            columns: ["receiver_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          created_at: string
          id: string
          listing_id: string | null
          read: boolean
          type: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          listing_id?: string | null
          read?: boolean
          type: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          listing_id?: string | null
          read?: boolean
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_color: string | null
          avatar_url: string | null
          bio: string | null
          created_at: string
          id: string
          initials: string | null
          location: string | null
          name: string
          program: string | null
          reply_time: string | null
          verified: boolean
          year: number | null
        }
        Insert: {
          avatar_color?: string | null
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          id: string
          initials?: string | null
          location?: string | null
          name: string
          program?: string | null
          reply_time?: string | null
          verified?: boolean
          year?: number | null
        }
        Update: {
          avatar_color?: string | null
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          id?: string
          initials?: string | null
          location?: string | null
          name?: string
          program?: string | null
          reply_time?: string | null
          verified?: boolean
          year?: number | null
        }
        Relationships: []
      }
      saved_listings: {
        Row: {
          created_at: string
          listing_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          listing_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          listing_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "saved_listings_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "saved_listings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      increment_listing_views: {
        Args: { listing_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database['public']

// Row aliases used by mappers and repositories.
export type ProfileRow = DefaultSchema['Tables']['profiles']['Row']
export type ListingRow = DefaultSchema['Tables']['listings']['Row']
export type SavedListingRow = DefaultSchema['Tables']['saved_listings']['Row']
export type MessageRow = DefaultSchema['Tables']['messages']['Row']
export type NotificationRow = DefaultSchema['Tables']['notifications']['Row']
export type BlockRow = DefaultSchema['Tables']['blocks']['Row']

export type ListingCondition = 'Like new' | 'Good' | 'Fair'
export type ListingStatus = 'active' | 'sold'
