// Generated by Supabase MCP — do not hand-edit.
// Regenerate: npx supabase gen types typescript --project-id fznliobjdeeyhictbepl > src/types/database.ts
// AX-102 complete: replaces the hand-written stopgap now that the project is provisioned.
//
// MANUAL ADDITION (pending regen): the `blocks` table + BlockRow alias were
// hand-added alongside migration 0001/0002 (RLS block support). Re-running the
// generator after the migration is applied will reproduce them; drop this note
// once it does.
//
// MANUAL ADDITION (pending regen): `messages.read_at` was hand-added alongside
// migration 0008 (read receipts). Same deal — regenerate after applying 0008.
//
// MANUAL ADDITION (pending regen): `profiles.bio` was hand-added alongside
// migration 0003 (AX-301 onboarding). Drop this note once regenerated.
//
// MANUAL ADDITION: the `conversation_list` view was hand-added with tight
// nullability. NOTE: the generator emits every view column as nullable (PG
// can't infer NOT NULL through a view) — after regenerating, keep this
// hand-tightened Views entry rather than the generated one.
//
// MANUAL ADDITION (pending regen): the `increment_listing_views` function was
// hand-added alongside migration 0007 (AX-111 view counter RPC). Drop this
// note once regenerated.
//
// MANUAL ADDITION (pending regen): the `my_listing_save_counts` function was
// hand-added alongside migration 0006 (AX-401 save counts). Drop this note
// once regenerated.
//
// MANUAL ADDITION (pending regen): the `delete_own_account` function was
// hand-added alongside migration 0010 (AX-704 account deletion RPC). Drop
// this note once regenerated.
//
// MANUAL ADDITION (pending regen): the `reports` table + ReportRow alias were
// hand-added alongside migration 0011 (AX-703 report/block). Same deal —
// regenerate after applying 0011.
//
// MANUAL ADDITION (pending regen): the `reports_queue` view (Studio/service_role
// only — no repository queries it, so no row alias) was hand-added alongside
// migration 0012 (AX-707 compliance triage queue). Drop this note once
// regenerated.
//
// MANUAL ADDITION (pending regen): `notifications.actor_id`/`read_at` were
// hand-added alongside migration 0013 (AX-601/602 notification generation).
// Drop this note once regenerated.
//
// MANUAL ADDITION (pending regen): the `create_test_notification` function was
// hand-added alongside migration 0017 (dev test-notification RPC). Same deal.
//
// MANUAL ADDITION (pending regen): the `follows` table + FollowRow alias were
// hand-added alongside migration 0019 (persisted profile follows). Drop this
// note once regenerated.
//
// MANUAL ADDITION (pending regen): the `reviews` table + ReviewRow alias were
// hand-added alongside migration 0020 (seller reviews). Drop this note once
// regenerated.
//
// MANUAL ADDITION (pending regen): the `listing_edit_requests` table +
// ListingEditRequestRow alias, and the `is_listing_engaged`/`apply_listing_edit`
// functions, were hand-added alongside migration 0021 (listing edit review
// flow). Drop this note once regenerated.
//
// Boundary rule: only src/repositories/ imports these types.
// Screens and hooks speak domain types from src/types/index.ts, never row types.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      blocks: {
        Row: {
          blocked_id: string
          blocker_id: string
          created_at: string
        }
        Insert: {
          blocked_id: string
          blocker_id: string
          created_at?: string
        }
        Update: {
          blocked_id?: string
          blocker_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "blocks_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "blocks_blocked_id_fkey"
            columns: ["blocked_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      follows: {
        Row: {
          created_at: string
          followee_id: string
          follower_id: string
        }
        Insert: {
          created_at?: string
          followee_id: string
          follower_id: string
        }
        Update: {
          created_at?: string
          followee_id?: string
          follower_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "follows_follower_id_fkey"
            columns: ["follower_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follows_followee_id_fkey"
            columns: ["followee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_edit_requests: {
        Row: {
          created_at: string
          id: string
          listing_id: string
          proposed_category: string | null
          proposed_condition: string | null
          proposed_image_urls: string[] | null
          proposed_thumb_urls: string[] | null
          proposed_title: string | null
          requester_id: string
          reviewed_at: string | null
          status: string
        }
        Insert: {
          created_at?: string
          id?: string
          listing_id: string
          proposed_category?: string | null
          proposed_condition?: string | null
          proposed_image_urls?: string[] | null
          proposed_thumb_urls?: string[] | null
          proposed_title?: string | null
          requester_id: string
          reviewed_at?: string | null
          status?: string
        }
        Update: {
          created_at?: string
          id?: string
          listing_id?: string
          proposed_category?: string | null
          proposed_condition?: string | null
          proposed_image_urls?: string[] | null
          proposed_thumb_urls?: string[] | null
          proposed_title?: string | null
          requester_id?: string
          reviewed_at?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "listing_edit_requests_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listing_edit_requests_requester_id_fkey"
            columns: ["requester_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      listings: {
        Row: {
          category: string | null
          condition: string | null
          created_at: string
          description: string | null
          id: string
          image_urls: string[]
          is_free: boolean
          is_trade: boolean
          pickup: string | null
          price: number
          seller_id: string
          status: string
          thumb_urls: string[]
          title: string
          views: number
        }
        Insert: {
          category?: string | null
          condition?: string | null
          created_at?: string
          description?: string | null
          id?: string
          image_urls?: string[]
          is_free?: boolean
          is_trade?: boolean
          pickup?: string | null
          price?: number
          seller_id: string
          status?: string
          thumb_urls?: string[]
          title: string
          views?: number
        }
        Update: {
          category?: string | null
          condition?: string | null
          created_at?: string
          description?: string | null
          id?: string
          image_urls?: string[]
          is_free?: boolean
          is_trade?: boolean
          pickup?: string | null
          price?: number
          seller_id?: string
          status?: string
          thumb_urls?: string[]
          title?: string
          views?: number
        }
        Relationships: [
          {
            foreignKeyName: "listings_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          body: string
          created_at: string
          id: string
          listing_id: string | null
          read_at: string | null
          receiver_id: string
          sender_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          listing_id?: string | null
          read_at?: string | null
          receiver_id: string
          sender_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          listing_id?: string | null
          read_at?: string | null
          receiver_id?: string
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_receiver_id_fkey"
            columns: ["receiver_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          actor_id: string | null
          created_at: string
          id: string
          listing_id: string | null
          read: boolean
          read_at: string | null
          type: string
          user_id: string
        }
        Insert: {
          actor_id?: string | null
          created_at?: string
          id?: string
          listing_id?: string | null
          read?: boolean
          read_at?: string | null
          type: string
          user_id: string
        }
        Update: {
          actor_id?: string | null
          created_at?: string
          id?: string
          listing_id?: string | null
          read?: boolean
          read_at?: string | null
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_color: string | null
          avatar_url: string | null
          bio: string | null
          created_at: string
          id: string
          initials: string | null
          location: string | null
          name: string
          program: string | null
          reply_time: string | null
          verified: boolean
          year: number | null
        }
        Insert: {
          avatar_color?: string | null
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          id: string
          initials?: string | null
          location?: string | null
          name: string
          program?: string | null
          reply_time?: string | null
          verified?: boolean
          year?: number | null
        }
        Update: {
          avatar_color?: string | null
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          id?: string
          initials?: string | null
          location?: string | null
          name?: string
          program?: string | null
          reply_time?: string | null
          verified?: boolean
          year?: number | null
        }
        Relationships: []
      }
      reports: {
        Row: {
          created_at: string
          id: string
          reason: string
          reporter_id: string
          status: string
          target_listing_id: string | null
          target_type: string
          target_user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          reason: string
          reporter_id: string
          status?: string
          target_listing_id?: string | null
          target_type: string
          target_user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          reason?: string
          reporter_id?: string
          status?: string
          target_listing_id?: string | null
          target_type?: string
          target_user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_target_user_id_fkey"
            columns: ["target_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_target_listing_id_fkey"
            columns: ["target_listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      reviews: {
        Row: {
          body: string
          created_at: string
          id: string
          rating: number
          reviewer_id: string
          seller_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          rating: number
          reviewer_id: string
          seller_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          rating?: number
          reviewer_id?: string
          seller_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reviews_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_reviewer_id_fkey"
            columns: ["reviewer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      saved_listings: {
        Row: {
          created_at: string
          listing_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          listing_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          listing_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "saved_listings_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "saved_listings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      conversation_list: {
        Row: {
          body: string
          created_at: string
          id: string
          listing_id: string | null
          partner_id: string
          read_at: string | null
          receiver_id: string
          sender_id: string
          unread_count: number
        }
        Relationships: []
      }
      // service_role only (see 0012's revoke) — no repository queries it; kept
      // here for schema fidelity with what a real gen-types run would emit.
      reports_queue: {
        Row: {
          created_at: string
          id: string
          reason: string
          reporter_email: string | null
          reporter_id: string
          reporter_name: string | null
          status: string
          target_listing_id: string | null
          target_listing_seller_id: string | null
          target_listing_title: string | null
          target_type: string
          target_user_email: string | null
          target_user_id: string | null
          target_user_name: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      increment_listing_views: {
        Args: { listing_id: string }
        Returns: undefined
      }
      my_listing_save_counts: {
        Args: Record<PropertyKey, never>
        Returns: { listing_id: string; saves: number }[]
      }
      delete_own_account: {
        Args: Record<PropertyKey, never>
        Returns: undefined
      }
      create_test_notification: {
        Args: Record<PropertyKey, never>
        Returns: undefined
      }
      is_listing_engaged: {
        Args: { p_listing_id: string }
        Returns: boolean
      }
      apply_listing_edit: {
        Args: { p_edit_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database['public']

// Row aliases used by mappers and repositories.
export type ProfileRow = DefaultSchema['Tables']['profiles']['Row']
export type ListingRow = DefaultSchema['Tables']['listings']['Row']
export type SavedListingRow = DefaultSchema['Tables']['saved_listings']['Row']
export type MessageRow = DefaultSchema['Tables']['messages']['Row']
// One inbox thread: the last message's columns plus partner_id/unread_count.
// A strict superset of MessageRow, so mappers accept it as a last message.
export type ConversationListRow = DefaultSchema['Views']['conversation_list']['Row']
export type NotificationRow = DefaultSchema['Tables']['notifications']['Row']
export type BlockRow = DefaultSchema['Tables']['blocks']['Row']
export type ReportRow = DefaultSchema['Tables']['reports']['Row']
export type FollowRow = DefaultSchema['Tables']['follows']['Row']
export type ReviewRow = DefaultSchema['Tables']['reviews']['Row']
export type ListingEditRequestRow = DefaultSchema['Tables']['listing_edit_requests']['Row']

export type ListingStatus = 'active' | 'sold'
